---
- hosts: localhost
  roles:
    - { role: fedora, become: true, when: ansible_distribution == 'Fedora' }
    - { role: ubuntu, become: true, when: ansible_distribution == 'Ubuntu' }
    - { role: install, become: true }
    - { role: configs, become: false }
    - { role: fin, become: true }


  vars:
    pkgs:     # get and install pkg from os pkg manager
      - vim
      - terminator
      - tilda
      - screen
      - mc
      - ncdu
      - net-tools
      - nmap
      - telnet
      - wget
      - curl
      - jq
      - git
      - python-pip
      - htop
      - tree
      - pluma
      - pwgen
      - yamllint
      - virtualenv
      - zip
      - unzip
      - siege
      - i3
      - i3status
      - dmenu
      - i3lock
      - xbacklight
      - feh
      - conky
      - conky-manager
    pipa:     # install pkg for pip
      - awscli
      - aws-shell
      - awsscout2
      - ovhcli
    snap:     # Download and install snapd pkg
      - pycharm-community
      - slack
      - spotify
      - remmina
      - atom
      - vscode
      - fast
    walls:    # Download Wallpapers
      - https://w.wallhaven.cc/full/3k/wallhaven-3kxgm9.png
      - https://w.wallhaven.cc/full/2k/wallhaven-2kyyw9.jpg
      - https://w.wallhaven.cc/full/j5/wallhaven-j5x92m.jpg
      - https://w.wallhaven.cc/full/1j/wallhaven-1j9o9v.png
      - https://w.wallhaven.cc/full/4y/wallhaven-4yd8x4.jpg
    alias:    # OS own aliases set in '/etc/bashrc' or '/etc/bash.bashrc' depend on base OS
      - "alias ll='ls -alh'"
      - "alias fuckit='shutdown -h now'"
      - "alias fixit='reboot'"
      - "alias krakow='curl wttr.in/krakow'"
    dirs:     # Directory structure in ~/Documents/
      - projects/_archive
      - wiki
      - git
      - scripts
      - cloud/aws
      - cloud/azure
      - cloud/gcp
      - cloud/ovh
      - cloud/alibaba
      - cloud/oracle
