---
- hosts: localhost
  roles:
    - { role: fedora, become: true, when: ansible_distribution == 'Fedora' }
    - { role: ubuntu, become: true, when: ansible_distribution == 'Ubuntu' }
    - { role: install, become: true }
    - { role: configs, become: false }
    - { role: fin, become: true }

  vars:
    pkgs:
      - vim
      - terminator
      - tilda
      - screen
      - mc
      - ncdu
      - net-tools
      - nmap
      - telnet
      - wget
      - curl
      - jq
      - git
      - python-pip
      - htop
      - tree
      - pluma
      - pwgen
      - yamllint
      - virtualenv
      - zip
      - unzip
      - siege
      - i3
      - i3status
      - dmenu
      - i3lock
      - xbacklight
      - feh
      - conky
      - conky-manager
    pipa:
      - awscli
      - aws-shell
      - awsscout2
      - ovhcli
    snap:
      - pycharm-community
      - slack
      - spotify
      - remmina
      - atom
      - vscode
      - fast
    walls:
      - https://w.wallhaven.cc/full/3k/wallhaven-3kxgm9.png
      - https://w.wallhaven.cc/full/2k/wallhaven-2kyyw9.jpg
      - https://w.wallhaven.cc/full/j5/wallhaven-j5x92m.jpg
      - https://w.wallhaven.cc/full/1j/wallhaven-1j9o9v.png
      - https://w.wallhaven.cc/full/4y/wallhaven-4yd8x4.jpg
