---
- name: "Install Fedora pkg"
  dnf:
    name: "{{ pkgs }}"
    state: latest

- name: "Install Fedora specified pkg"
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - '@Development Tools'
    - python3-pyOpenSSL
    - libselinux-python

- name: "Setting Snapd Link"
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link