---
- name: "Install Fedora pkg"
  dnf:
    name: "{{ pkgs }}"
    state: latest

- name: "Install Fedora specified pkg"
  dnf:
    name: '@Development Tools'
    state: latest

- name: "Setting Snapd Link"
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link