---
- name: "Install Fedora pkg"
  dnf:
    name: "{{ pkgs }}"
    state: latest

- name: "Install Fedora specified pkg"
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - '@Development Tools'
    - python3-pyOpenSSL
    - libselinux-python
    - snapd
    - dnf-plugins-core

- name: "Get Docker Repo"
  template:
    src: docker-ce.j2
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: "Install Docker-ce"
  dnf:
    name: docker-ce
    state: latest

- name: "Setting Snapd Link"
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link