---
- name: "Install Fedora pkg"
  dnf:
    name: "{{ pkgs }}"
    state: latest

- name: "Install Fedora specified pkg"
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - '@Development Tools'
    - python3-pyOpenSSL
    - libselinux-python
    - snapd
    - dnf-plugins-core

#- name: "Get Docker repo"
#  command: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
#  ignore_errors: true

- name: "Install Docker"
  dnf:
    name: "{{ item }}"
    state: latest
    update_cache: true
  ignore_errors: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Setting Snapd Link"
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: "Install i3"
  dnf:
    name: "{{ item }}"
    state: latest
  tags: [ never, i3 ]
  loop:
