---
- name: "Set User Alias"
  lineinfile:
    path: "{% if ansible_distribution == 'Fedora' %}/etc/bashrc{% elif ansible_distribution == 'Ubuntu' %}/etc/bash.bashrc{% endif %}"
    line: "{{ item }}"
  become: true
  loop:
    - "alias ll='ls -alh'"
    - "alias fuckit='shutdown -h now'"
    - "alias fixit='reboot'"
    - "alias krakow='curl wttr.in/krakow'"

- name: "Create Dir Tree in ~/Documents/"
  file:
    path: "{{ ansible_user_dir }}/Documents/{{ item }}"
    state: directory
  loop:
    - projects/_archive
    - wiki
    - git
    - scripts
    - cloud/aws
    - cloud/azure
    - cloud/gcp

- name: "Set .vimrc"
  template:
    src: vimrc.j2
    dest: "{{ ansible_user_dir }}/.vimrc"

- name: "Set i3 config"
  template:
    src: i3-config.j2
    dest: "{{ ansible_user_dir }}/.config/i3/config"

- name: "Create ~/.ssh"
  file:
    path: "{{ ansible_user_dir }}/.ssh/"
    state: directory

- name: "Generate OpenSSL private key"
  openssl_privatekey:
    state: present
    path: "{{ ansible_user_dir }}/.ssh/id_rsa"

- name: "Generate OpenSSL public key"
  openssl_publickey:
    state: present
    path: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    privatekey_path: "{{ ansible_user_dir }}/.ssh/id_rsa"
    format: OpenSSH

- name: "Set config in ~/.ssh"
  template:
    src: ssh-config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: 0600

- name: "Create tree in ~/.config"
  file:
    path: "{{ ansible_user_dir }}/.config/{{ item }}"
    state: directory
  loop:
    - tilda
    - autostart
    - terminator

- name: "Set Terminator Config"
  template:
    src: terminator-config.j2
    dest: "{{ ansible_user_dir }}/.config/terminator/config"
    mode: 0664

- name: "Set Tilda Config"
  template:
    src: tilda-config.j2
    dest: "{{ ansible_user_dir }}/.config/tilda/config_0"
    mode: 0664

- name: "Set Tilda to Autostart"
  template:
    src: tilda-autostart.j2
    dest: "{{ ansible_user_dir }}/.config/autostart/tilda.desktop"
    mode: 0664

- name: "Download Wallpapers :)"
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_user_dir }}/Pictures"
  with_items:
    - "{{ walls }}"