---
- name: "Install Ubuntu pkg"
  apt:
    name: "{{ pkgs }}"
    update_cache: true
    state: latest

- name: "Install Ubuntu specified pkg"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - build-essential