---
- name: "Install Ubuntu pkg"
  apt:
    name: "{{ pkgs }}"
    update_cache: true
    state: latest

- name: "Install Ubuntu specified pkg"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - build-essential
    - software-properties-common

- name: "Add Docker GPG Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Set Docker to Stable release"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: "Install Docker-ce"
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: "Add Ansible Repo"
  apt_repository:
    repo: ppa:ansible/ansible

- name: "Install Ansible"
  apt:
    name: ansible
    state: latest
    update_cache: true
