---
- name: "Install Ubuntu pkg"
  apt:
    name: "{{ pkgs }}"
    update_cache: true
    state: latest

- name: "Add Docker GPG Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Install Ubuntu specified pkg"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - build-essential
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - docker-ce